name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Build completed"

      - name: Start test web server
        run: |
          docker run -d -p 8080:80 nginx
          sleep 10

      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "http://localhost:8080"

      - name: Build Docker image
        run: |
        docker build -t username/gala_projekts:latest .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
           image-ref: "username/gala_projekts:latest"

           